# Generated by Django 6.0.3 on 2026-03-26 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_postmodel_author_postmodel_content_postmodel_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postmodel',
            options={'ordering': ['-date_created']},
        ),
    ]
